# numpy tutorial  

numpy is a array preprocessing package. it provides a high- performance multidimensional array object , tools for working with these arrays. it is the fundamental package for scientific computing in python.

An array class in numpy called as ndarray.

# numpy array creation

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6]) # this is rank 1 array
print(arr)

[1 2 3 4 5 6]


In [2]:
arr =np.array([[1,2,3],[4,5,6]])# this is rank 2 array
print(arr)

[[1 2 3]
 [4 5 6]]


numpty array using tuple--

In [3]:
arr =np.array((1,2,3,4,5))# numpy array creation using tuple 
print(arr)

[1 2 3 4 5]


# Accessing the array index

In [5]:
arr =np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
print(arr[:,::3])

[[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]


# Basic array operations

In [19]:
arr1 =np.array([[1,2], [3,4]])
arr2 =np.array([[5,6],[7,8]])
print(arr1)
print()

print(arr2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


adding 1 to arr1  and adding 2 to arr2

In [20]:
print(arr1+1)# aad 1 in arr1
print()
print(arr2+2)# add 2 in arr2

[[2 3]
 [4 5]]

[[ 7  8]
 [ 9 10]]


In [37]:
print(" arr1 dimenssion is ",arr1.ndim)

 arr1 dimenssion is  2


In [42]:
print("arr1 size is ",arr1.size)

arr1 size is  4


In [43]:
print("arr1 type is ",type(arr1))

arr1 type is  <class 'numpy.ndarray'>


In [44]:
print("arr1 shape is ",arr1.shape)

arr1 shape is  (2, 2)


binary operation on both arr1 and arr2

In [21]:
print(arr1+arr2)# adding the both arry

[[ 6  8]
 [10 12]]


In [23]:
print(arr1.sum())# sum of arr1

10


# Datatypes in numpy

In [26]:
arr =np.array([1,2,3])
print("array type is ",arr.dtype)

array type is  int32


In [28]:
arr =np.array([1.0,2.0,3.4])
print("array type is ",arr.dtype)

array type is  float64


In [32]:
arr =np.array([1,2,3,4],dtype =np.int64)# forced datatype
print("array type is ",arr.dtype)

array type is  int64


# Math operation on datatype array

In [36]:
arr1 =np.array([[2,3],[3,4]],dtype =np.int64)
arr2 =np.array([[5.6,6.4],[7.1,8.3]],dtype =np.float64)

sum =np.add(arr1,arr2)
print(sum)

print()
sqrt =np.sqrt(arr1)
print(sqrt)

[[ 7.6  9.4]
 [10.1 12.3]]

[[1.41421356 1.73205081]
 [1.73205081 2.        ]]


# numpy array methods

Methods in Numpy
all()
any()
take()
put()
apply_along_axis()
apply_over_axes()
argmin()
argmax()
nanargmin()
nanargmax()
amax()
amin()
insert()
delete()
append()
around()
flip()
fliplr()
flipud()
triu()
tril()
tri()
empty()
empty_like()
zeros()
zeros_like()
ones()
ones_like()
full_like()
diag()
diagflat()
diag_indices()
asmatrix()
bmat()
eye()
roll()
identity()
arange()
place()
extract()
compress()
rot90()
tile()
reshape()
ravel()
isinf()
isrealobj()
isscalar()
isneginf()
isposinf()
iscomplex()
isnan()
iscomplexobj()
isreal()
isfinite()
isfortran()
exp()
exp2()
fix()
hypot()
absolute()
ceil()
floor()
degrees()
radians()
npv()
fv()
pv()
power()
float_power()
log()
log1()
log2()
log10()
dot()
vdot()
trunc()
divide()
floor_divide()
true_divide()
random.rand()
random.randn()
ndarray.flat()
expm1()
bincount()
rint()
equal()
not_equal()
less()
less_equal()
greater()
greater_equal()
prod()
square()
cbrt()
logical_or()
logical_and()
logical_not()logical_xor()
array_equal()
array_equiv()
sin()
cos()
tan()
sinh()
cosh()
tanh()
arcsin()
arccos()
arctan()
arctan2()

# Some important numpy methods

In [45]:
arr=np.zeros((3,4))# make the 2D metrix with all zeros
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
arr =np.arange(0,10,1)#return evenly spaced values within given an interval
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
arr =np.linspace(1,10)# returns evenly spaced values within a given interval
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [55]:
arr =np.ones((3,4))#make a 2D metrix with all ones
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
